services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: ModuleBankDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
      - authapi

  authapi:
    build:
      context: .
      dockerfile: AuthApi/Dockerfile
    ports:
      - "5210:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  postgres_data:  